[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"
#keyfile = "keyfile.toml"

[jamulus]
source = "github"
github = "jamulussoftware/jamulus"
use_max_tag = true
include_regex = '^r(\d+)_(\d+)_(\d+)$'
from_pattern = '^r(\d+)_(\d+)_(\d+)$'
to_pattern = '\1.\2.\3'

[mamba]
source = "github"
github = "brummer10/Mamba"
use_max_tag = true
prefix = "v"

# note: unquoted dots in section names cause errors
["mclk.lv2"]
source = "github"
github = "x42/mclk.lv2"
use_max_tag = true
prefix = "v"

[midiomatic]
source = "github"
github = "SpotlightKid/midiomatic"
use_max_tag = true
prefix = "v"

[ola]
source = "github"
github = "OpenLightingProject/ola"
use_max_tag = true

[python-pyjacklib]
source = "pypi"
pypi = "pyjacklib"

[python-rtmidi]
source = "pypi"
pypi = "python-rtmidi"

[qjackcapture]
source = "pypi"
pypi = "QJackCapture"

[string-machine]
source = "github"
github = "jpcima/string-machine"
use_max_tag = true
prefix = "v"

[tuxguitar]
source = "regex"
url = "https://sourceforge.net/projects/tuxguitar/rss?path=/TuxGuitar"
regex = 'tuxguitar-(\d+\.\d+(?:\.\d+)?)-src.tar.gz'
encoding = "utf-8"

[vcvrack]
source = "github"
github = "VCVRack/Rack"
use_max_tag = true
prefix = "v"

[ykchorus]
source = "github"
github = "SpotlightKid/ykchorus"
use_max_tag = true
prefix = "v"
