[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"
keyfile = "keyfile.toml"

[abcm2ps]
source = "github"
github = "lewdlime/abcm2ps"
use_max_tag = true
prefix = "v"

# note: unquoted dots in section names cause errors
["aether.lv2"]
source = "github"
github = "Dougal-s/Aether"
use_max_tag = true
include_regex = '^v[\.\d]+$'
prefix = "v"

[clap]
source = "github"
github = "free-audio/clap"
use_max_tag = true

[elephantdsp-roomreverb]
source = "github"
github = "cvde/RoomReverb"
use_max_tag = true
prefix = "v"

[faustlive]
source = "github"
github = "grame-cncm/faustlive"
use_max_tag = true
include_regex = '^\d+(\.\d+)+$'

[glasscoder]
source = "github"
github = "ElvishArtisan/GlassCoder"
use_latest_release = true
prefix = "v"

[gnome-shell-extension-gsjackctl]
source = "github"
github = "cbix/gsjackctl"
use_max_tag = true
prefix = "v"

[hpklinux]
source = "regex"
url = "https://www.audioscience.com/internet/download/linux_drivers.htm"
regex = 'hpklinux_(.*).tar.gz.*stable'

[jack-matchmaker]
source = "pypi"
pypi = "jack-matchmaker"

[jalv-select]
source = "github"
github = "brummer10/jalv_select"
use_max_tag = true
prefix = "v"

[jamulus]
source = "github"
github = "jamulussoftware/jamulus"
use_max_tag = true
include_regex = '^r(\d+)_(\d+)_(\d+)$'
from_pattern = '^r(\d+)_(\d+)_(\d+)$'
to_pattern = '\1.\2.\3'

[klick]
source = "github"
github = "Allfifthstuning/klick"
use_max_tag = true

[kpp]
source = "github"
github = "olegkapitonov/Kapitonov-Plugins-Pack"
use_max_tag = true
include_regex = '^\d+(\.\d+)+$'

[mamba]
source = "github"
github = "brummer10/Mamba"
use_max_tag = true
prefix = "v"

["mclk.lv2"]
source = "github"
github = "x42/mclk.lv2"
use_max_tag = true
prefix = "v"

[midimonster]
source = "github"
github = "cbdevnet/midimonster"
use_max_tag = true
prefix = "v"

[midiomatic]
source = "github"
github = "SpotlightKid/midiomatic"
use_max_tag = true
prefix = "v"

[ninjam-server]
source = "github"
github = "cbix/ninjam"
use_max_tag = true
include_regex = '^ninjamsrv\/v[\.\d]+$'
prefix = "ninjamsrv/v"

[ola]
source = "github"
github = "OpenLightingProject/ola"
use_max_tag = true

[paulxstretch]
source = "github"
github = "essej/paulxstretch"
use_max_tag = true
prefix = "v"

[python-pyjacklib]
source = "pypi"
pypi = "pyjacklib"

[python-pysimplegui]
source = "pypi"
pypi = "PySimpleGUI"

[python-rtmidi]
source = "pypi"
pypi = "python-rtmidi"

[qjackcapture]
source = "pypi"
pypi = "QJackCapture"

[rakarrack-plus]
source = "github"
github = "Stazed/rakarrack-plus"
use_max_tag = true

[rtcqs]
source = "pypi"
pypi = "rtcqs"

[stone-phaser]
source = "github"
github = "jpcima/stone-phaser"
use_max_tag = true
prefix = "v"

[string-machine]
source = "github"
github = "jpcima/string-machine"
use_max_tag = true
prefix = "v"

["swh-plugins.lv2"]
source = "github"
github = "swh/lv2"
use_max_tag = true
prefix = "v"

[tuxguitar]
source = "regex"
url = "https://sourceforge.net/projects/tuxguitar/rss?path=/TuxGuitar"
regex = 'tuxguitar-(\d+\.\d+(?:\.\d+)?)-src.tar.gz'
encoding = "utf-8"

[vcf-lv2]
source= "github"
github = "linuxmao-org/vcf-lv2"
use_max_tag = true
prefix = "v"

[vcvrack]
source = "github"
github = "VCVRack/Rack"
use_max_tag = true
prefix = "v"

[vcvrack-21khz]
source = "github"
github = "netboy3/21kHz-rack-plugins"
use_max_tag = true

[vcvrack-8mode]
source = "github"
github = "8Mode/8Mode-VCV_Modules"
use_max_tag = true

[vcvrack-aaronstatic]
source = "github"
github = "aaronstatic/AaronStatic_modules"
use_max_tag = true
prefix = "v"

[vcvrack-ahornberg]
source = "github"
github = "Ahornberg/Ahornberg-VCV-Modules"
use_max_tag = true
prefix = "v"

[vcvrack-alikins]
source = "github"
github = "alikins/Alikins-rack-plugins"
use_max_tag = true
prefix = "v"

[vcvrack-collection-one]
source = "github"
github = "scanner-darkly/vcv-collection-one"
use_max_tag = true
prefix = "v"

[vcvrack-computerscare]
source = "github"
github = "freddyz/computerscare-vcv-modules"
use_max_tag = true
prefix = "v"

[vcvrack-cvly]
source = "github"
github = "Lyqst/cvly-modules"
use_max_tag = true

[vcvrack-freesurface]
source = "github"
github = "freesurfacemodules/FreeSurface"
use_max_tag = true
prefix = "v"

[vcvrack-goodsheperd]
source = "github"
github = "jensschulze/GoodSheperd"
use_max_tag = true

[vcvrack-sonusmodular]
source = "gitlab"
gitlab = "sonusdept/sonusmodular"
use_max_tag = true

[vcvrack-zetacarinae]
source = "github"
github = "mhampton/ZetaCarinaeModules"
use_max_tag = true
prefix = "v"

[ykchorus]
source = "github"
github = "SpotlightKid/ykchorus"
use_max_tag = true
prefix = "v"
