[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"
#keyfile = "keyfile.toml"

[mamba]
source = "github"
github = "brummer10/Mamba"
use_max_tag = true
from_pattern = '^v'
to_pattern = ""

[midiomatic]
source = "github"
github = "SpotlightKid/midiomatic"
use_max_tag = true
from_pattern = '^v'
to_pattern = ""

[tuxguitar]
source = "regex"
url = "http://www.tuxguitar.com.ar/download.html"
regex = 'Latest Version (\d+\.\d+(?:\.\d+)?)'
encoding = "utf-8"

[string-machine]
source = "github"
github = "jpcima/string-machine"
use_max_tag = true
from_pattern = '^v'
to_pattern = ""
