[__config__]
oldver = "old_ver.json"
newver = "new_ver.json"
#keyfile = "keyfile.toml"

[abcm2ps]
source = "github"
github = "lewdlime/abcm2ps"
use_max_tag = true
prefix = "v"

# note: unquoted dots in section names cause errors
["aether.lv2"]
source = "github"
github = "Dougal-s/Aether"
use_max_tag = true
include_regex = '^v[\.\d]+$'
prefix = "v"

[hpklinux]
source = "regex"
url = "https://www.audioscience.com/internet/download/linux_drivers.htm"
regex = 'hpklinux_(.*).tar.gz'

[jack-matchmaker]
source = "pypi"
pypi = "jack-matchmaker"

[jalv-select]
source = "github"
github = "brummer10/jalv_select"
use_max_tag = true
prefix = "v"

[jamulus]
source = "github"
github = "jamulussoftware/jamulus"
use_max_tag = true
include_regex = '^r(\d+)_(\d+)_(\d+)$'
from_pattern = '^r(\d+)_(\d+)_(\d+)$'
to_pattern = '\1.\2.\3'

[klick]
source = "github"
github = "Allfifthstuning/klick"
use_max_tag = true

[kpp]
source = "github"
github = "olegkapitonov/Kapitonov-Plugins-Pack"
use_max_tag = true
include_regex = '^\d+(\.\d+)+$'

[mamba]
source = "github"
github = "brummer10/Mamba"
use_max_tag = true
prefix = "v"

["mclk.lv2"]
source = "github"
github = "x42/mclk.lv2"
use_max_tag = true
prefix = "v"

[midimonster]
source = "github"
github = "cbdevnet/midimonster"
use_max_tag = true
prefix = "v"

[midiomatic]
source = "github"
github = "SpotlightKid/midiomatic"
use_max_tag = true
prefix = "v"

[ola]
source = "github"
github = "OpenLightingProject/ola"
use_max_tag = true

[python-pyjacklib]
source = "pypi"
pypi = "pyjacklib"

[python-rtmidi]
source = "pypi"
pypi = "python-rtmidi"

[qjackcapture]
source = "pypi"
pypi = "QJackCapture"

[rakarrack-plus]
source = "github"
github = "Stazed/rakarrack-plus"
use_max_tag = true

[stone-phaser]
source = "github"
github = "jpcima/stone-phaser"
use_max_tag = true
prefix = "v"

[string-machine]
source = "github"
github = "jpcima/string-machine"
use_max_tag = true
prefix = "v"

["swh-plugins.lv2"]
source = "github"
github = "swh/lv2"
use_max_tag = true
prefix = "v"

[tuxguitar]
source = "regex"
url = "https://sourceforge.net/projects/tuxguitar/rss?path=/TuxGuitar"
regex = 'tuxguitar-(\d+\.\d+(?:\.\d+)?)-src.tar.gz'
encoding = "utf-8"

[vcf-lv2]
source= "github"
github = "linuxmao-org/vcf-lv2"
use_max_tag = true
prefix = "v"

[vcvrack]
source = "github"
github = "VCVRack/Rack"
use_max_tag = true
prefix = "v"

[ykchorus]
source = "github"
github = "SpotlightKid/ykchorus"
use_max_tag = true
prefix = "v"
